services:
  database:
    image: postgres:17-alpine3.20
    container_name: database-service
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: "./.env"

  backend:
    build: .
    image: backend-image
    container_name: backend-service
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./:/app
    depends_on:
      - database

volumes:
  postgres_data:
